### ISSUE TITLE
Specify parent tab for newely created tabs

### ISSUE THREAD

**Issue by shishkin-pavel** [infokiller/web-search-navigator#113]
This can be done using `openerTabId` optional parameter for `tabs.create()` [func](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#Parameters)
This improvement will greatly affect interoperation with addons such as TreeStyleTab.

**Comment by infokiller** [comment]
Thanks for reporting, makes sense.
This should be a pretty easy fix, but it will probably take some time to reach the web store (both for Chrome and Firefox).

**Comment by nicchristeller** [comment]
Would this also fix the issue below?

**Actions:**
* Have a tab open and focused
* Open a new tab with keyboard shortcut
* Search something in the omnibox, taking you to a Google results page
* Navigate to a result, and open it in new tab (so it opens in background) with shortcuts from this extension
* Close the current tab with ctrl+w

**Expected:**
Result tab that was opened in background is focused

**Actual:**
Whichever tab was selected in Step 1 is re-focused

**Comment by infokiller** [comment]
@nicchristeller I'm not sure, but once I get to fixing this I will test it
