### ISSUE TITLE
first result as callout not detected

### ISSUE THREAD

**Issue by ghost** [infokiller/web-search-navigator#122]
Hey. Nice plugin. It's really a big time saver! I noticed a small issue. For some search results, when there's a callout/snippet associated with the first result, the extension does not detect that link as the first result. So, in this case, the extension doesn't mark it as the first one and additionally it cannot be navigated to. For example, if you type in the search query "microsoft excel strikethrough" you should see what I'm talking about. Thanks again for the great plugin!!

**Comment by infokiller** [comment]
Hey, thanks for the bug report.
I can confirm this issue. Will try to fix it soon, shouldn't be hard.

**Comment by infokiller** [comment]
This is now fixed in the master branch. Keeping it open till it's released in the Chrome Web Store.
