### ISSUE TITLE
Cannot remove Websites permissions

### ISSUE THREAD

**Issue by BastianKubaile** [infokiller/web-search-navigator#128]
As in #127  mentioned there is no way to remove permissions of certain websites even though options.html looks like it is possible.

**Comment by Gazorby** [comment]
I think the main problem here is that [webext-dynamic-content-scripts](https://github.com/fregante/webext-dynamic-content-scripts) only watch for `permissions.request()` and not `permissions.remove()`. So it register the script correctly on new domains but do not unregister it

**Comment by infokiller** [comment]
I just tested this, and it seems that the permission is actually removed (judging by what `chrome.permissions.contains` and `chrome.permissions.onRemoved` report), although for some reason Chrome keeps showing the URLs in the site access (and it also doesn't request permissions from the user if they enable it again).
