### ISSUE TITLE
Can this tool be used for other search engines?

### ISSUE THREAD

**Issue by LaPeste** [infokiller/web-search-navigator#129]
Hi,
the initiative is great. However, I dropped google search a while ago and I was wondering if you are thinking about adding support for other search engines which are still big players:

- Bing
- StartPage (what I use)
- DuckDuckGo
- maybe 1 or 2 more.

Thank you for the consideration.

**Comment by infokiller** [comment]
Hi,

Yes this is actually a work in progress- see https://github.com/infokiller/web-search-navigator/issues/82 and some recent PRs that added support for startpage (https://github.com/infokiller/web-search-navigator/pull/124) and youtube (https://github.com/infokiller/web-search-navigator/pull/127).

So the current development version supports StartPage, but it's not released to the store yet, as I want to further test it before then, and probably add a few more fixes along the way. I hope I'll have time to work on this "soon".

**Comment by LaPeste** [comment]
You've just put a smile on my face!
Thank you so much for the amazing work!

**Comment by vcfvct** [comment]
Hi @infokiller , since now the bing chatgpt integration work decently, I am gradually switching my search engine from Google to Bing, Is there any plan to support Bing? :) Thank you!

**Comment by infokiller** [comment]
@vcfvct thanks for the kind words, I doubt I'll have time to do it in the near term, but I welcome PRs
