### ISSUE TITLE
Keyboard shortcuts don't work consistently in the images tab

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#133]

**Comment by infokiller** [comment]
I tested this in Firefox and it actually worked.
In chrome incognito it works inconsistently for me. Not sure if it's related to another extension I'm using.

**Comment by ysmike** [comment]
For me, keyboard shortcuts work fine in images tab during incognito mode (with the rest of my extensions also enabled). However, during a regular session (non-incognito mode), the keyboard shortcuts do not work in the images tab even with all extensions but web-search-navigator disabled.

**Comment by linh-yesware** [comment]
Can't speak for all shortcuts, but I think I know why the 'focus search box' shortcut is broken. It [assumes the search box is a DOM element with the selector `'#searchform input[name=q]'`](https://github.com/infokiller/web-search-navigator/blob/2252062ab347cb06ea8ecf3e4fdcd9b1132b8043/src/searchEngines.js#L69) and in the Images tab, that's no longer the case. On my machine, the search box now has the class `JSAgYe` and ID `REsRA`:

![image](https://user-images.githubusercontent.com/8398315/74270426-30e2b700-4cd9-11ea-9fb9-deb620ddbf32.png)

 (don't judge; I was looking for a very important GIF)

Google probably started uglifying class names recently, possibly as some sort of guard against reverse-engineering the page like we're doing here 😬 If that new class name remains constant, we can fix this by simply hardcoding it in. Or maybe we can select the search box with `input[role="combobox"]` instead, which seems like it should remain stable.

**Comment by infokiller** [comment]
Thanks for your input!
I'll try to fix it in the next round of fixes/improvements, should be easy enough.

**Comment by williamfiset** [comment]
For me, just going to the images tab makes the whole extension totally unusable :(

I can hop between the search tab, the videos tab, and all other tabs just fine, but as soon as I go to the images tab I can't regain focus of the navbar or switch to any other tab. I tested this in normal chrome with only this extension.

**Comment by infokiller** [comment]
@williamfiset till this is fixed, you can work around that by using a keyboard shortcut for back. I use a private unreleased extension for this to set the keyboard shortcuts for back/forward (can release it if people are interested), but there's probably other extensions around for that.

**Comment by williamfiset** [comment]
Thanks for the tip, I think in Chrome you can use ⌘ + ← to return to the previous page, which point you can continue using the extension normally. This is a doable workaround as it doesn't require me to use my mouse, but I feel like a proper fix is still needed.

**Comment by eggbean** [comment]
Really great that this is working as well now. But if I can suggest what I think would be a minor improvement:

When you highlight a picture and press ENTER, the preview pane opens on the right. Once the preview pane is closed again using ESC, instead of the previous thumbnail being selected, the search text entry box is.

**Comment by infokiller** [comment]
Yes @eggbean I agree the search box should not be selected in this case. I will try to fix it.
Re the thumbnail outline highlighting, that's actually the built in behavior of image search, the results navigation of the extension is disabled there right now (which is why you can only navigate with arrow keys and not the keys configured in the extension).
I'll see if I can fix that too before the next release.
