### ISSUE TITLE
Verbatim Search

### ISSUE THREAD

**Issue by GaXve** [infokiller/web-search-navigator#134]
Would it be a plausible idea to incorporate a keyboard shortcut key for Verbatim Search?

**Comment by infokiller** [comment]
Yes, definitely. I plan to do a round of improvements and fix a bunch of issues that are currently open, but there's no ETA yet.
PRs welcome, of course.

**Comment by GaXve** [comment]
Gotcha! I know it's very easy to come up with ideas and make suggestions,
and that's it's another thing entirely to actually implement them. I use
your extension every day, so I'm happy to do anything I can to make it
better. Unfortunately, my programming days are far in the past (I
programmed basic, cobol, and I believe one of the first versions of Visual
Basic). I'm slowly getting back into the programming scene. It's just going
to be a while before I am well versed in whatever is needed to program
extensions (HTML, CSS or Javascript I believe?).

I guess the only other contribution I can make at the moment are
suggestions. I'll share this last idea, in case you might find it of value.
I was thinking it might be useful to be able to open a search engine
(image, video, etc.) but in a new tab. Either giving focus, or opening them
in the background. I often keep my initial search queries as a base line.
That way if my searches don't yield what I'm looking for, I don't have to
retype the whole thing a start all over. The user could assign to different
hotkeys to one search engine (e.g. "i" for image search in current tab,
"Ctrl + Shift + i" for image search in a new tab).

Anyhow, even though I have very limited skills in programming at the
moment, if there's anything I might do to help out, let me know!

Cheers!



*Stefane Guevremont*

E-mail: stefane.guevremont@gmail.com

**Comment by infokiller** [comment]
Thanks, frankly the pending improvements/fixes (including this issue) are just blocked on me having time to implement them (and testing a new version properly), so there's not much you can do now.
Re opening another search mode (images, videos, etc) in a new tab: why don't you use the browser's back navigation for this?
