### ISSUE TITLE
Not working on Chrome Version 79.0.3945.130

### ISSUE THREAD

**Issue by Olshansk** [infokiller/web-search-navigator#136]
Chrome has a setting called `Pressing Tab on a webpage highlights links, as well as form fields` which doesn't quite do the same thing as thing as this extension. I tried enabling and disabling this with no luck...

Also, I have `Focus on first search result automatically after the page loads` enabled, but it doesn't seem to do anything.

Is there a known issue?

**Comment by infokiller** [comment]
No, that's strange, it works for me in Chromium `80.0.3987.100` (and worked in all previous versions as well).
Did you try incognito?

**Comment by Olshansk** [comment]
I think one of my other extensions is interferring with it actually. Not sure which one, but I do not think the extension is at fault.
