### ISSUE TITLE
Focusing with tab and then pressing enter stopped working

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#145]
This is a great extension, but not being able to get to these other links is the biggest problem for me.

I do not mind using TAB and SHIFT-TAB to navigate to these links, but when I press ENTER, what happens is that that link will be activated at the same time as the link that this extension is marking, which then opens.

Is there any way of deactivating the extension momentarily?

_Originally posted by @eggbean in https://github.com/infokiller/web-search-navigator/issues/97#issuecomment-611332200_

**Comment by infokiller** [comment]
I think this is now fixed in the latest master branch.
Just so that I can verify, do you have an example search query I can test?
Screenshots will also be useful to verify I'm looking at the same results.

**Comment by eggbean** [comment]
![image](https://user-images.githubusercontent.com/815311/85190251-5b0f3b80-b2ae-11ea-8485-c2aa6aba25ba.png)

* I used the up/down arrow keys and have marked link 1

* Then I used SHIFT+TAB until link 2 is marked (bold) and press ENTER but link 1 opens instead.

**Comment by infokiller** [comment]
This works for me. Can you try the latest master branch to see if it's fixed for you?

Run this in a shell:
```sh
git clone https://github.com/infokiller/web-search-navigator
cd web-search-navigator
yarn install && yarn build
```

Then load the unpacked extension from the `src` folder.
If you don't want to install/run git/yarn, let me know and I can also send a zip file of the build.
Also let me know if you need help on loading an unpacked chrome extension.

**Comment by eggbean** [comment]
> Then load the unpacked extension from the src folder.

I have built it using yarn, but I am not sure what I am supposed to do afterwards.
After building the only difference seems to be the contents of `,/node_modules`. Is that right?

**Comment by infokiller** [comment]
The contents of `node_modules` change when you run `yarn install`, but after you run `yarn build` it should also add a few more files to the `src` directory.

Anyway, I actually discovered a method that is easier and safer from mistakes. First cd to the project directory and then:

```sh
# Update the project to latest version
git pull
# Install dependencies and build the extension
yarn install && yarn build
# Run a browser with the extension. Replace '--target chromium' with "--target firefox-desktop" for Firefox.
yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=hare+vs+rabbit' --target chromium
```

This will open a new browser profile with only the extension already loaded.

**Comment by eggbean** [comment]
Could you package this so that I can try it? Thanks.

**Comment by infokiller** [comment]
[wsn.zip](https://github.com/infokiller/web-search-navigator/files/4810283/wsn.zip)

**Comment by eggbean** [comment]
Excellent. Thanks, it's working fine now 😃
