### ISSUE TITLE
Extension Doesn't Seem To Work 

### ISSUE THREAD

**Issue by Olshansk** [infokiller/web-search-navigator#148]
I'm on the latest version of chrome and extension simply doesn't work for me.

I have the `Focus on first search result automatically after the page loads` option enabled, but it doesn't automatically focus on the first result.

When I click "tab", it goes to google's "Skip to main content" button.

Not sure what I have to configure to make use of the extension, so any help would be appreciated!

I've tried disabling all my other extensions to make sure nothing was interfering.

**Comment by infokiller** [comment]
Sorry for the bad experience, let's see if we can figure this out.
What OS are you using?
Did you try the [Firefox Addon](https://addons.mozilla.org/firefox/addon/web-search-navigator/)?

**Comment by Olshansk** [comment]
Thanks for the quick reply! I'm using macOS Catalina.

The Firefox add worked fine actually!

Do you have any suggestions of logs I can potentially look into in the developer console to figure out what's going on?

**Comment by infokiller** [comment]
Hmm, not that I can think of right now.
Do you see the arrow next to the search results?
Here's how it looks on my browser when googling for "whatever":

![image](https://user-images.githubusercontent.com/10516814/83464786-89051b00-a47a-11ea-8348-d1158f921653.png)

**Comment by Olshansk** [comment]
I've opened an incgonito window and online enabled this one extension (see the screenshot below). The arrow does not show up.

![Screen Shot 2020-06-02 at 8 50 10 AM](https://user-images.githubusercontent.com/1892194/83541239-3e04fb00-a4ae-11ea-8e5b-94fceda8a5f4.png)

**Comment by infokiller** [comment]
Thanks, can you please check what is the CSS path of the search result element using the chrome dev console?
See https://github.com/infokiller/web-search-navigator/issues/149#issuecomment-637670489

**Comment by Olshansk** [comment]
Followed up in the other thread: https://github.com/infokiller/web-search-navigator/issues/149#issuecomment-638960750

**Comment by infokiller** [comment]
Closing this to centralize the discussion in #149
