### ISSUE TITLE
Release 0.4.x for Firefox

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#157]
Related Chrome issue: #156 

@mancze I tested the latest master branch on Firefox and it worked in basic tests, but it would be great if you could also do it, and if everything seems fine, release it after a few days. Chrome added a gradual rollout feature which I will use for this release (for example you can release to only 20% of users initially), not sure if Firefox supports it.

BTW, I used `web-ext` to test the extension and it's pretty great: you can run:

```sh
yarn install && yarn build
yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target firefox-desktop
```

Then it opens a new Firefox browser profile with only the dev version of the extension installed, and automatically reloads it if the source files change.

**Comment by infokiller** [comment]
0.4.7 is released for Chrome (and 0.4.5 was released a few days prior).
@mancze can I help with the firefox release?

**Comment by mancze** [comment]
Yup, I'm on it. Sorry for the delay.

**Comment by mancze** [comment]
v0.4.13 has been just published: https://addons.mozilla.org/en-US/firefox/addon/web-search-navigator/versions/ .
