### ISSUE TITLE
"j" key is not moving to next result, but "k" key is moving to next result instead of previous

### ISSUE THREAD

**Issue by jyclam** [infokiller/web-search-navigator#179]
**Web search navigator**
Version 0.4.11 through Chrome stoe

**Chrome**
Version 84.0.4147.89 (Official Build) (64-bit)

Is this fixed in Version 0.4.13?

**Comment by infokiller** [comment]
Yup

**Comment by jyclam** [comment]
Awesome :)

**Comment by infokiller** [comment]
It seems that the new version was approved and released a few hours ago.
Can you please verify that the issue is fixed?
To verify that the extension was updated, go to <chrome://extensions/?id=cohamjploocgoejdfanacfgkhjkhdkek> and check that version is set to `0.4.13`

**Comment by jyclam** [comment]
Yep! Version 0.4.13 fixes this issue. Thanks for being super quick on the fix

**Comment by infokiller** [comment]
Apologies for introducing it in the first place :)
