### ISSUE TITLE
How much effort will it require to make it work with GitHub?

### ISSUE THREAD

**Issue by tiagorodriguessimoes** [infokiller/web-search-navigator#210]
I really like this extension and I use it daily. I'd like to have it working when I'm navigating on github. 

I want to navigate between projects (results of a search), to jump between comments (on pull requests), etc

I can also contribute to make it happen if necessary.

**Comment by mancze** [comment]
When you open options for the add-on in your browser you can enable it for Github under Alternative search engines. You can give it a try. However, I don't use it for Github so I'm not sure whether it works well or not.

**Comment by tiagorodriguessimoes** [comment]
Thank you!
