### ISSUE TITLE
The YouTube Kbd Nav Extension: a way of better integration with YouTube

### ISSUE THREAD

**Issue by psygo** [infokiller/web-search-navigator#217]
I'm a big fan of this extension. And, so, I decided to create [my own for YouTube][youtube_kbd_nav].

I know you guys already have some support for YouTube, but I think that something more specific would be better and easier to manage, otherwise this extension might become too big.

At any rate, I hope that what I did there can shine a light on some useful functionalities. Take a look and tell me what you think, I would really appreciate it. It's not working as well as I expected for [Firefox][firefox], but on [Chrome and Microsoft Edge (Chromium)][chrome], it seems to be working perfectly, or, at least, as I imagined (and tested).

[chrome]: https://chrome.google.com/webstore/detail/youtubekbdnav/lfhpmfgaahemloddkjioinadcoighoih?hl=en&authuser=0
[firefox]: https://addons.mozilla.org/en-US/firefox/addon/youtube-kbd-nav/
[youtube_kbd_nav]: https://github.com/FanaroEngineering/youtube_kbd_nav

**Comment by infokiller** [comment]
Thanks for reaching out! I'll play with your extension once I get a few minutes to spare for this, but it makes sense that a separate extension will work better.

**Comment by infokiller** [comment]
@psygo I finally had some time to test it, so I started a new Chromium profile and installed it as the only extension but it didn't work (see screenshot below). As for feedback, what would probably be missing for me is the ability to change keyboard shortcuts (I don't see any extension options).

![image](https://user-images.githubusercontent.com/10516814/132123834-c63f1155-087a-4473-bacb-c9d12f5447be.png)

**Comment by psygo** [comment]
Sorry that it didn't work. But could you please tell me what the problem really is? Because I still use this extension to this day, and it is still working over here &mdash; and I use the Chrome Store version.

What exactly were you trying to test in the screenshot above? The <kbd>z</kbd> and <kbd>x</kbd> shortcuts, I suppose?

> As for feedback, what would probably be missing for me is the ability to change keyboard shortcuts

Yes, I wanted to add this as a new feature at some point, but didn't have the time. And, since the extension never really got popular, I also lacked motivation.

**Comment by infokiller** [comment]
My bad, it does work- I just didn't guess the shortcuts are `z` and `x` (tested `j`/`k` and up/down).

**Comment by psygo** [comment]
I didn't use <kbd>j</kbd>/<kbd>k</kbd> because they were already taken by YouTube's UI.
