### ISSUE TITLE
I, V, M, N key shortcuts not working

### ISSUE THREAD

**Issue by eggbean** [infokiller/web-search-navigator#229]
For the last week or so the key shortcuts for viewing the Images, Video, Maps, New, etc tabs on the Google SERPs page have not been working. I had to wait until I could test on another computer and OS before making this issue. I can confirm that it isn't working on Linux or Windows. I am not sure what else has broken.

**Comment by infokiller** [comment]
Yes, it seems that this is caused by a change in the HTML of Google. I pushed a new version for Chrome yesterday that should fix this (it does for me), can you please check it?

**Comment by infokiller** [comment]
@mancze can you please do another release for Firefox as well?

**Comment by mancze** [comment]
Yup, I'm on it.

**Comment by mancze** [comment]
New version for Firefox released.

**Comment by eggbean** [comment]
Yes, it seems to be working well now. Thanks.

**Comment by infokiller** [comment]
Seems this is broken again now because of yet another Google update. I fixed it on master again and will release another version for Chrome.
@mancze can you please release another version for Firefox?
Sorry for asking again, I hope this time the fix is more robust to changes in Google's DOM.

**Comment by infokiller** [comment]
I just released it for Chrome.

**Comment by mancze** [comment]
No trouble. Version 0.4.17 released for Firefox.
