### ISSUE TITLE
Startpage functionality in Firefox?

### ISSUE THREAD

**Issue by blakeelias** [infokiller/web-search-navigator#241]
Hi all,

This is more of a question than a bug. This was the only place I could find to contact the developers, so thought I'd just post here.

I'm curious if using the Firefox extension (downloaded from here: https://addons.mozilla.org/en-US/firefox/addon/web-search-navigator/) allows tabbing through search results on Startpage.com. The README mentions support for Startpage.... but when I load the extension into my browser, I'm not seeing anything different when I do my searches, and when I try pressing `i` or `j` to move to previous/next result, nothing seems to happen. Any help here? Is startpage.com still supported?

Thanks!

**Comment by infokiller** [comment]
Hi, did you enable StartPage support in the extension options?

**Comment by blakeelias** [comment]
Oh.... didn't know I had to do that.

I'll go check those options and let you know-- hopefully that should do it, I guess!


________________________________

**Comment by blakeelias** [comment]
Alright, I enabled it now and it works!
Maybe some messaging about this in the description that shows up in the
Firefox extensions install page?

--
Blake Elias

**Comment by infokiller** [comment]
Thanks for the feedback @blakeelias, I added a clarification in the docs, and we will update it in the Chrome and Firefox pages in the next release 
@mancze: can you please use https://github.com/infokiller/web-search-navigator/blob/master/assets/browser_stores_description.txt to update the description now or in the next release?
