### ISSUE TITLE
Don't scroll to first result when there is a google card

### ISSUE THREAD

**Issue by vpshastry** [infokiller/web-search-navigator#29]
When there is a google cards like when you search 'weather' or 'define <word>' the page is automatically scrolled down to the first google results after the ads. This makes I can't even see that google info. In case of google's cards lets don't scroll it down.

**Comment by infokiller** [comment]
I can confirm this.

**Comment by infokiller** [comment]
@vpshastry this issue should be fixed on Chrome. You can already test it on master, but I will also do a release soon.

**Comment by vpshastry** [comment]
Great! Thanks. Will try it soon.
