### ISSUE TITLE
Brave Search support

### ISSUE THREAD

**Issue by bulutfatih** [infokiller/web-search-navigator#292]
Since I switched my main search engine from Google to Brave Search, I miss this extension and accessibility on search results. I would like to see this extension working on Brave Search.

I already implemented this feature and ~~will open~~ opened a pull request.

**Comment by infokiller** [comment]
Thanks a lot, merged
Will take me some time to make a new release and test it, but you can run it from a local build for now. I'll keep this issue open till I make the new release.

**Comment by bulutfatih** [comment]
@infokiller I didn't update Brave to descriptions. Do you want me to do that, or can you do it?

**Comment by infokiller** [comment]
Do you mean the README? just updated it

**Comment by bulutfatih** [comment]
README.md, manifest.json, browser_stores_description.txt
I think these files should be updated. 🤔

**Comment by infokiller** [comment]
Thanks, forgot about manifest.json. Updated it too and other files (including CHANGELOG.md).

**Comment by infokiller** [comment]
@mancze I'm about to do a Chrome release, please do the same for Firefox

**Comment by infokiller** [comment]
@bulutfatih I wanted to take this opportunity to get your feedback as a first time contributor: how was the experience of adding a new search engine? were the docs in the README ok?
If there's anything that can be improved, please let me know.

Thanks

**Comment by bulutfatih** [comment]
> @bulutfatih I wanted to take this opportunity to get your feedback as a first time contributor: how was the experience of adding a new search engine? were the docs in the README ok?
> If there's anything that can be improved, please let me know.
> 
> Thanks

It took time to understand the logic, how things work. Maybe we should add more comments to important functions or improve the documentation in the `search_engines.js` file.
Targeting the highlight element and the container was a bit difficult. I figured it out after a few tries.
Reference commit wasn't clear, I read the code of Google and Startpage.
Need better eslint and prettier configurations.
README was good.

**Comment by mancze** [comment]
@infokiller Done, version 0.4.18 available for Firefox: https://addons.mozilla.org/cs/firefox/addon/web-search-navigator/

**Comment by mancze** [comment]
Uhm, actually I think this issue was not closed before my comment. I got a little confused, sorry. Reopening for that reason.

**Comment by infokiller** [comment]
Thanks @mancze 
Yes the Chrome review is taking some time, I'll close the issue once it's released there
