### ISSUE TITLE
YouTube results navigation is broken

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#296]

**Comment by infokiller** [comment]
OK this actually works from a test I just did, but it's hard to see the frame of the current selection with a dark background.
@jinusean does it not work for you? did you enable support in the options?

**Comment by jinusean** [comment]
Sorry but i've switched over to youtube specific extension for youtube.

**Comment by nsrCodes** [comment]
Seems to still be broken. Keybindings seem to work neither on home nor on search results. Tried
- Incrementally increasing delay on extension initialization upto 2 seconds
- Reloading _( as it seemed to work for someone here - #337 )_

**Comment by infokiller** [comment]
@nsrCodes home wasn't implemented, but search results are. I also see unstable behavior but when I set the delay to 500 ms I  can no longer reproduce it.
Can you try to reload a few times and see if it works sometimes? that's the behavior I saw without the delay (with a delay it always works).
Anyway, a proper fix should be implemented so I'll reopen.

**Comment by infokiller** [comment]
@nsrCodes I believe this should be fixed now, if you can test the latest dev version and confirm it would be great, see https://github.com/infokiller/web-search-navigator#building-for-development

**Comment by nsrCodes** [comment]
Everything works perfectly. Tried both by manually installing the build and also running the `web-ext` command (on both chrome and firefox) . Thanks 😄

**Comment by infokiller** [comment]
Thanks a lot @nsrCodes for testing this so quickly! I'll publish a release soon with the fixes and will close this issue once it hits the store
