### ISSUE TITLE
Extension does not work for some queries

### ISSUE THREAD

**Issue by hikmet517** [infokiller/web-search-navigator#297]
For example, when I search "brooklyn nine nine", I can't navigate or see anchor. But, when I unchecked the option "Include Cards" it starts working again.

I'm using Firefox 91.0.2 on Arch Linux.

**Comment by infokiller** [comment]
Thanks for the report, I can confirm. Will try to fix ASAP.

**Comment by infokiller** [comment]
Fixed on master, now I need to release a new version.
