### ISSUE TITLE
Youtube search results wont show the wrapper box

### ISSUE THREAD

**Issue by iitjee** [infokiller/web-search-navigator#337]
On an existing video page, if we search for a new query, the resulting page doesn't show the white box wrapper. However on refresh it does

**Comment by infokiller** [comment]
Thanks for reporting, confirmed.

**Comment by infokiller** [comment]
@iitjee  I believe this should be fixed now, if you can test the latest dev version and confirm it would be great, see https://github.com/infokiller/web-search-navigator#building-for-development

**Comment by infokiller** [comment]
OK, this is actually not fixed yet- will try to fix it now

**Comment by infokiller** [comment]
Now it should be fixed in the dev version
