### ISSUE TITLE
No UI indicator when navigating though recommended sub pages

### ISSUE THREAD

**Issue by nsrCodes** [infokiller/web-search-navigator#357]
unlike #97 the existing key bindings work when the top search result also has other pages to recommend, but the navigation arrow is not visible when navigating through them.

_Results like these :_
![Screenshot from 2022-02-17 08-50-56](https://user-images.githubusercontent.com/57226514/154398731-82b94372-0e96-45d1-aac3-9ad08a831dca.png)

_crude demo_
![web-navigator](https://user-images.githubusercontent.com/57226514/154398673-376650ee-4775-42d0-8775-339adc2cfcec.gif)

**Comment by infokiller** [comment]
Hi, thanks for the clear bug report, I was able to reproduce it. I'll try to fix it ASAP

**Comment by infokiller** [comment]
@nsrCodes I believe this should be fixed now, if you can test the latest dev version and confirm it would be great, see https://github.com/infokiller/web-search-navigator#building-for-development

**Comment by nsrCodes** [comment]
Yup, works perfectly now. Thanks
