### ISSUE TITLE
Navigate through popup windows which appear on new websites

### ISSUE THREAD

**Issue by dakellyad** [infokiller/web-search-navigator#365]
Something I've found with using this extension is that so many websites that you open for the first time will have either a popup to ask for your cookie/data uses choices, or "disable adblocker", and you can't navigate through these with your keyboard, destroying the whole point of using your keyboard for google. 
This might be quite a stretch as it would require extending the scope of this extension to basically every website, but even just being able to navigate the most common types of popups (which often seem to be similar) would make a huge difference. 

Don't know how others found this issue, but for me basically more than 50% of websites I open for the first time require me to answer the stupid popups.

**Comment by infokiller** [comment]
Seems way out of scope for this extension, have you tried uBlock Origin with easylist-cookies enabled?
