### ISSUE TITLE
Release v0.4.20 for Firefox

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#380]
@mancze 0.4.20 which was just released in the Chrome Web Store fixes multiple issues (see https://github.com/infokiller/web-search-navigator/blob/master/CHANGELOG.md for a few of them), so it would be great to have a firefox release as well.

Also, for future releases, can you please add me as an Author of the extension in the Firefox Developer Hub?
This way I won't have to bother you with a new release each time there is one

Thanks!

**Comment by mancze** [comment]
I've built and uploaded a new version for Firefox. Hopefully it will be approved soon.

**Comment by mancze** [comment]
I'll happily add you as an author to Firefox store, let's agree on the email to use over email.

**Comment by infokiller** [comment]
@mancze thanks! I confirm I got your email to gsearch.navigator and I'll respond there
