### ISSUE TITLE
Youtube search result navigation broken

### ISSUE THREAD

**Issue by nsrCodes** [infokiller/web-search-navigator#405]
**Bug**: When navigation the search results on youtube the up and down navigation seem to jump a few steps whereas the left and right arrows work correctly. But this is unintuitive. 

**Predicting**: I haven't looked into it yet, but I am assuming it's happening because the `griddNavigation` boolean for the Youtube search engine object isn't set to false after being routed from the youtube home page. 

Sometimes even refereshing the search results page doesn't solve this. This seems like a separate issue (_but I might be wrong_)

> Sorry, it's probably my code that broke this 😰

**Comment by infokiller** [comment]
@nsrCodes did you get a change to look at this?
Not sure if related, but I just committed https://github.com/infokiller/web-search-navigator/commit/c80a782452a2bd462ac6a7b171be3a802c898421 which fixes a YT issue

**Comment by nsrCodes** [comment]
I haven't been able to find time to fix this, but I tried with the latest code on master, and the result page navigation still seems broken
