### ISSUE TITLE
Google search results with Google job embeds

### ISSUE THREAD

**Issue by nsrCodes** [infokiller/web-search-navigator#406]
When job related searches that sometimes have a google job dialog embedded between the results, the hotkeys navigate through both the jobs (_which is still acceptable_) and the filter tags

https://user-images.githubusercontent.com/57226514/177135053-d0bfefa5-1510-4693-9839-ac13b5734a6c.mp4

**Comment by infokiller** [comment]
Thanks for reporting! I can't trigger the jobs widget, not sure if this is an experiment or I just need to access it from another location, but I'll try with a VPN

**Comment by infokiller** [comment]
I'm able to reproduce this when connected to a VPN server in Chicago
