### ISSUE TITLE
Add pre-commit for formatting & linting

### ISSUE THREAD

**Issue by margunwa123** [infokiller/web-search-navigator#434]
Hello! I have noticed that there is no pre-commit hook installed on this repo, and when running `yarn check`, i got this error:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/54434884/192200596-e54f745a-d001-4a6d-898c-40ca4c2e7f76.png">

I'm thinking on creating a pull request that have 
- some pre-commit hooks (using husky), 
- adding lint-staged to auto-add linted / formatted files to staged,
- also will try to match the configuration from codefactor to prettier / eslint and fix the error

Any thoughts about this? Thankyou!

**Comment by infokiller** [comment]
Hi @margunwa123 thanks for your suggestion and sorry for the slow response
Does `yarn run check` still fail for you on current master?
It works for me and on Github's CI.

Regardless, I'm open to adding pre-commit hooks, so feel free to open a PR.

Thanks
