### ISSUE TITLE
Custom arrow

### ISSUE THREAD

**Issue by davidp88** [infokiller/web-search-navigator#439]
Custom arrow size,as it's now slightly small to see

**Comment by infokiller** [comment]
This can be achieved using custom CSS (see https://github.com/infokiller/web-search-navigator/issues/427 for reference)

**Comment by davidp88** [comment]
drfgggfgf

**Comment by davidp88** [comment]
427 reference is for vertical line, I added and saw

**Comment by infokiller** [comment]
I don't understand your comment, if you want to make changes to the arrow you need to tweak the CSS

**Comment by davidp88** [comment]
pls provide the code

**Comment by infokiller** [comment]
No time for this

**Comment by davidp88** [comment]
after a few days,give

**Comment by infokiller** [comment]
No time, locking issue
