### ISSUE TITLE
[Feature Request] Is it possible to add shortcuts for going to the next/previous category of results?

### ISSUE THREAD

**Issue by MahdiNazemi** [infokiller/web-search-navigator#455]
Some Google search results, usually related to shopping, start with images. WSN selects those images, and one has to press <kbd>j</kbd> a few times, e.g., eight times, before going to the next category of results that links to external sites.
These images are placed periodically after a few links to external sites, so browsing all results with WSN becomes tedious.

I think it would be beneficial to add support for jumping to the next/previous category of results, e.g., tweets, images, videos, etc. For example, pressing something like <kbd>shift</kbd>+<kbd>j</kbd> selects the first result of the next category, so one can quickly go to the next category if not interested in the current category of results.

**Comment by infokiller** [comment]
I welcome PRs for this (without setting any new default shortcuts- users that want this can set them themselves), but I have little interest in it personally, so unless this gets a massive number of votes I won't prioritize this
