### ISSUE TITLE
[Bug Report] Up/Down shortcuts are broken when Google continuously loads new results

### ISSUE THREAD

**Issue by MahdiNazemi** [infokiller/web-search-navigator#464]
Google may be testing a new feature that loads new results as you get to the end of the page (instead of having results on separate pages).

I suspect WSN modifies the page on load and, therefore, does not support the newly shown results.

**Comment by infokiller** [comment]
I can't reproduce this, any specific queries where you see this behavior?

**Comment by MahdiNazemi** [comment]
All my queries show the same behavior. I just Googled "google search
results" and saw more results loading as I scrolled down.
Would a video recording or copy of the HTML/CSS help?

**Comment by infokiller** [comment]
Thanks for offering, but I'm afraid I'd need a fully working page with JS to be able to fix this.

**Comment by infokiller** [comment]
I'm able to reproduce this when connected to a VPN server in Chicago

**Comment by MahdiNazemi** [comment]
It looks like this feature [will be rolled out globally in the near future](https://www.theverge.com/2022/12/6/23495973/google-search-desktop-continuous-scrolling). There is [a setting to disable this feature](https://www.google.com/preferences?hl=en&fg=1), but it does not have any effect in regions where continuous scrolling is available.

<img width="975" alt="Screenshot 2023-03-08 at 4 16 14 PM" src="https://user-images.githubusercontent.com/11276349/223882261-c7198ed0-3476-41ec-a750-0f2cb8ac32b3.png">

Can a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) detect such changes (similar to [the example here](https://stackoverflow.com/a/57316245)) and apply WSN customizations to the newly displayed results?

**Comment by infokiller** [comment]
Thanks @MahdiNazemi I think I fixed this on master, can you please clone the repo and run it in dev mode (see https://github.com/infokiller/web-search-navigator/issues/464) to verify if it works for you?

**Comment by infokiller** [comment]
@MahdiNazemi this is similar to https://github.com/bitcoin/bitcoin/issues/17190#issuecomment-1475704256
Just to confirm, when you navigate to the "more results" button using the extension, does it work?
If so, I consider this issue fixed, and a separate issue can be opened for implementing the params mentioned by the comment above.

**Comment by MahdiNazemi** [comment]
@infokiller, the extension can select "More results", but when I press <kbd>Enter</kbd>, it does not load more results in the same page. Instead, it loads a new page in the old Google search experience (Page 2). I can then use WSN's shortcuts like <kbd>H</kbd> and <kbd>L</kbd> keys to go to Page 1 or Page 3.

I am not sure if this should be addressed in this issue or a new issue. Please let me know how to proceed.

**Comment by MahdiNazemi** [comment]
>     * Sometimes, Google does not load new results when I get to the bottom of the page, and WSN selects the "More results" button. Pressing Enter on the selected "More results" button loads a new page similar to the old search experience. If instead of pressing Enter, I go up a few results with WSN by holding K such that "More results" goes out of the viewport and come back down by pressing J, I see the results loaded continuously.

I just learned that if I press <kbd>Space</kbd> on "More Results" instead of <kbd>Enter</kbd>, Google will load more results on the same page.

**Comment by infokiller** [comment]
Thanks for the update @MahdiNazemi 
I will keep the issue open till I release the new version

**Comment by eggbean** [comment]
This continuous scrolling has been enabled for me now in the UK and I hate it. I have `Continuous scroll` disabled in https://www.google.com/preferences#tabVal=1, but I can't get rid of it. So annoyed at Google doing something that I hate every few months.
