### ISSUE TITLE
Esc doesn't focus on input search box

### ISSUE THREAD

**Issue by bulutfatih** [infokiller/web-search-navigator#488]
It used to work before, but I realized that focusing on the search box when pressing ESC doesn't work anymore.

Search engine: Google
Browser: Chrome 111.0.5563.64
OS: macOS 13.2.1

Edit: Interestingly, I have 3 user profiles on my Chrome. It works with only one of them. I disabled all the other extensions, but didn't work. :/

**Comment by infokiller** [comment]
Did you try https://github.com/infokiller/web-search-navigator#troubleshooting ?

**Comment by bulutfatih** [comment]
I tried it, working with another profile. But I have no idea what is wrong with my profile. I disabled all the extensions, cleared browser data, reinstall the extension. Nothing works ¯\_(ツ)_/¯

**Comment by infokiller** [comment]
I'm unable to reproduce this. Does it work in Firefox?

**Comment by bulutfatih** [comment]
Yes, it works in Firefox.
I don't know how to reproduce this. Maybe I can create a new profile, and move all my data to there.
I'm closing the issue, sorry for disturbing.
