### ISSUE TITLE
[Feature Request] Mimic middle-click on "Open in a new background tab"

### ISSUE THREAD

**Issue by MahdiNazemi** [infokiller/web-search-navigator#496]
Currently, "Open in a new background tab" opens a new tab in the same Firefox container as the link search page. I use the [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) extension and have set my Isolation settings to open a new container on middle-click if the target belongs to a different domain or subdomain.

Is it possible to add an option to mimic the middle-click when the shortcut associated with "Open in a new background tab" is pressed?

I understand this may not be a popular feature, so I would be more than happy to start working on it myself and submit a PR. I would appreciate it if you could give me a few pointers on where to start.

I should probably try to modify one of the following blocks, right?
https://github.com/infokiller/web-search-navigator/blob/136bd59b5d8d5c64c94d8c80b6bc588ff56095f9/src/main.js#L510-L523
https://github.com/infokiller/web-search-navigator/blob/136bd59b5d8d5c64c94d8c80b6bc588ff56095f9/src/background.js#L1-L9

**Browser and OS**

- Browser: Firefox 111.0.1
- OS: macOS Ventura 13.2.1

**Comment by MahdiNazemi** [comment]
I am not proficient in javascript, but it looks like I can dispatch a middle-click event to a link element based on [this StackOverflow answer](https://stackoverflow.com/a/32868971).

Assuming all links have a default event listener for the `click` event, is something like the following reasonable?

```js
    this.register(getOpt('navigateNewTabBackgroundKey'), () => {
      const link = this.resultsManager.getElementToNavigate(true);
      if (link == null) {
        return true;
      }
      /*
      browser.runtime.sendMessage({
        type: 'tabsCreate',
        options: {
          url: link.href,
          active: false,
        },
      });
      */
      let middleClick = new MouseEvent( "click", { "button": 1, "which": 2 });
      link.dispatchEvent(middleClick);
      return false;
    });
```

**Comment by infokiller** [comment]
If you manage to get it working, feel free to send a PR, but please put this behind an option in the advanced section, and make it off by default.
