### ISSUE TITLE
Back/Forwards history with H/L (with shift) to work seamlessly with Vimium - please!

### ISSUE THREAD

**Issue by eggbean** [infokiller/web-search-navigator#501]
Hi, I have been using this extension for years and I cannot do without it. I have only recently started using Vimium and I love that too. I didn't try it before as I assumed that it would interfere with all the standard Chrome shortcuts that I know, as well as this extension, but it doesn't and it can be disabled on specific domain, so it works perfectly.

Vimium can go back/forwards in the browser history with H/L (capitals, with shift), which is very ergonomic, but that stops when this extension takes over on Google search. It would be fantastic if this extension had an option to enable back/forwards with H/L.

I had a look at main.js to see if I could do a fork myself, but I don't think I can.

**Comment by infokiller** [comment]
I'm using https://github.com/gdh1995/vimium-c without any issue.
All the keybindings are configurable, check the extension options. Try to remove the conflicting keybindings and see if it fixes the issue for you.

**Comment by infokiller** [comment]
> Hi, are you saying that the keybindings are configurable in web-search-navigator? 

Yes

> In the options I could not find anything for Back/Forwards. 

There are no keybindings assigned to these actions, but there are keybindings that use h/l (without shift, but they may cause the issue).
I would try to remove all the keybindings from web search navigator (via the options), see if it fixes the issue, then enable them till I find the issue.
You should also make sure you properly configured vimium. For example, try to disable web-search-navigator and see if back/forward works.

**Comment by eggbean** [comment]
Oh right, I think you have misunderstood my request. There isn't an issue. I was just asking if H/L could be binded to Back/Forwards in web-search-navigator in the same way they are in Vimium, so that they continue to work the same when I am on a Google, YouTube, or GitHub page, where I have Vimium disabled and web-search-navigator enabled.

Or many Vimium-C allows them to both be enabled at the same time or something?

**Comment by infokiller** [comment]
Binding back/forward is definitely outside the scope of this extension.
But there is a solution to your problem- partially disable vimium on these websites. Last time I used vimium it was possible, but if not it's definitely possible in vimium-c (which BTW was better in every aspect last I checked).

**Comment by eggbean** [comment]
Okay that sounds good. Cheers.
