### ISSUE TITLE
Doesn't seem to work with Brave Search on Firefox

### ISSUE THREAD

**Issue by Cr8zyIvan** [infokiller/web-search-navigator#514]
I've enabled permission to Web Search Navigator for Brave Search (https://search.brave.com), but I'm not getting any response from Web Search Navigator. It works flawlessly for Google Search.

I use a few Ad Blocker Add-Ons, I wonder if that might be the problem?

**Comment by infokiller** [comment]
I can't reproduce that. Please follow https://github.com/infokiller/web-search-navigator#troubleshooting

**Comment by Cr8zyIvan** [comment]
Apologies for not getting back to you earlier. Being on Firefox, it is a challenge to find a way to isolate your Add-Ons, especially when you use as many as I do. Firefox does not allow for Add-On managers and Disabling each Add-On one-by-one is very tedious.

I have tried web-search-navigator on Firefox's Nightly version, having only this one Add-On installed, and I encounter the same behaviour.

What happens is, when I check the "Enable on Brave Search" Option, web-search-navigator works as intended for that current Firefox session. If I open a second or third Firefox window, web-search-navigator stops working. I can get it to work again if I Uncheck-Check the "Enable on Brave Search" Option, but again, it works for that current Firefox session, and it stops working for every subsequent Firefox session.
