### ISSUE TITLE
[Bug] "Focus search box" no longer works

### ISSUE THREAD

**Issue by MahdiNazemi** [infokiller/web-search-navigator#515]
The current search box selector on Google is 
https://github.com/infokiller/web-search-navigator/blob/f87f5e22d1cc8286c7e7645a9255cfa94915a687/src/search_engines.js#L182
while the form element I see in my browser is
```html
<form action="/search" autocomplete="off" method="GET" role="search">
```
which includes a `textarea` child element that looks like one of the following
```html
<textarea class="gLFyf" jsaction="paste:puy29d;" id="APjFqb" maxlength="2048" name="q" rows="1" aria-activedescendant="" aria-autocomplete="both" aria-controls="Alh6id" aria-expanded="false" aria-haspopup="both" aria-owns="Alh6id" autocapitalize="off" autocomplete="off" autocorrect="off" autofocus="" role="combobox" spellcheck="false" title="Search" type="search" value="" aria-label="Search" data-ved="0ahUKEwi1zdbg3Mv-AhVYIUQIHQDJAEAQ39UDCAY">
```
```html
<textarea class="gLFyf" jsaction="paste:puy29d; mouseenter:MJEKMe; mouseleave:iFHZnf;" id="APjFqb" maxlength="2048" name="q" rows="1" aria-activedescendant="" aria-autocomplete="both" aria-controls="Alh6id" aria-expanded="false" aria-haspopup="both" aria-owns="Alh6id" autocapitalize="off" autocomplete="off" autocorrect="off" role="combobox" spellcheck="false" type="search" value="search trends" aria-label="Search" data-ved="0ahUKEwjNzdLE3sv-AhX8AzQIHR1FBxQQ39UDCAw">
```
so the updated selector would look like
```js
return 'form[role=search] textarea[name=q]'; 
```

~~I suspect this case is handled by `outsideSearchboxHandler` below~~
https://github.com/infokiller/web-search-navigator/blob/c164242d32b56f9580927b3dc4db8acc023b7006/src/main.js#L275-L311 ~~but it does not work correctly in my case.~~

**System Information:**
macOS Ventura (13.3.1)
Firefox 112.0.2

**Comment by infokiller** [comment]
Thanks for reporting, confirmed. Will be fixed soon.
