### ISSUE TITLE
Open tabs in same tab group

### ISSUE THREAD

**Issue by imeed166** [infokiller/web-search-navigator#524]
**Is your feature request related to a problem? Please describe.**
Hi, I'm always using tab groups, but when I try to open links with this extension, they open outside the current tab group

**Describe the solution you'd like**
An option in the settings, to open the links (foreground or background) in the same tab group

**Describe alternatives you've considered**
they are no alternatives, I have to use another extension like https://chrome.google.com/webstore/detail/google-search-keyboard-sh/iobmefdldoplhmonnnkchglfdeepnfhd to achieve this behaviour, but these extensions are not as good as this one in terms of stability, features and personalization.

**Additional context**

**Comment by infokiller** [comment]
Thanks for reporting this- I actually consider the current behavior a bug.
I will try to look into it later today, it should be easy to fix

**Comment by imeed166** [comment]
Awesome, thank you !!

**Comment by infokiller** [comment]
I just fixed this on master. You can run a dev version from current master (if you don't know how, lmk), or wait till it hits the web store

**Comment by imeed166** [comment]
I don't know how, but I don't want to bother, I have other things to do at the moment anyway. Thanks again, I'll wait for the update in the web store.
