### ISSUE TITLE
🗞️ Hackernews Support

### ISSUE THREAD

**Issue by Explosion-Scratch** [infokiller/web-search-navigator#544]
It'd be great to have these keyboard shortcuts on HackerNews as well.

**Comment by infokiller** [comment]
@Explosion-Scratch this feels out of scope because HN doesn't really have a search UI as far as I can tell.
There is however a very good extension that covers this: https://github.com/plibither8/refined-hacker-news
Closing, please do let me know if I missed anything

**Comment by Explosion-Scratch** [comment]
Sounds good =)
