### ISSUE TITLE
Enhance search result highlighting

### ISSUE THREAD

**Issue by flyboy101** [infokiller/web-search-navigator#56]
Is it advantegeous to have the focused result highlighted similarly to what DuckDuckGo does, i.e. with a background light colour (very light!) on the entire result filed, rather than having just the result title highlighted?

**Comment by infokiller** [comment]
In terms of design I prefer the way it is on DuckDuckGo.
I think we can add an option to change the way it looks, possibly supporting custom CSS by the user.

**Comment by flyboy101** [comment]
A result border highlight is implemented here: https://github.com/bluemirr5/web-keyboard-navigator
A better chromatic layout could be defined, though.

**Comment by BastianKubaile** [comment]
I would like to give the user the possibility to customize the CSS which does the highlighting, so basically expose search_results.css to them on the options page. [Loading](https://github.com/BastianKubaile/web-search-navigator/commit/2cc5818a332805ef33dd3a9a78dd6ec28a4e641a) the file into options.html is possible, but there seems to be no clear way on saving it. Saving it directly isn't possible, chrome.downloads is of no use either. One could save it in chrome.storage or  use this                 [API](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule), but both ways aren't nice solutions. I would like to hear feedback some feedback on this issue from you guys.

**Comment by infokiller** [comment]
Why is `chrome.storage` not nice?

**Comment by infokiller** [comment]
FWIW I looked into how vimium does it, and it uses `chrome.storage`

**Comment by BastianKubaile** [comment]
On a second thought loading the whole `search_results.css` file into `chrome.storage` is possible and styling the web pages is also possible. I think I will implement that this way then 👍

**Comment by infokiller** [comment]
I just implemented an experimental setting of custom CSS rules on master.
There are still some limitations because CSS doesn't support parent selectors, so you will have to style the element that is currently chosen by the extension, but I encourage you to try it out to see if you can implement what you want.
I will close this bug after this is released in Chrome.
