### ISSUE TITLE
[Bug]: google search open result in new windows always fails , when using  web-search-navigator shortcut.

### ISSUE THREAD

**Issue by thomasTAT** [infokiller/web-search-navigator#572]
### Related issues

- [X] I have searched the existing issues

### What happened?

in instead of opening in new windows, search result open in current tab.  I found two ways to trigger this:
Enable "Focus on first search result automatically after the page loads" and press Enter immediately after the search results appear.
Click the search bar, then click outside the search bar, and then immediately press Enter.

Opening search results in the current tab will terminate the AI response, which is inconvenient for users who use the AI sidebar for Google Search.
![image](https://github.com/infokiller/web-search-navigator/assets/109513632/8334f250-44c4-4f41-9713-0af88101bc66)

### Browsers

Microsoft Edge

### Other extensions

Yes

### Version

0.5.2

### Troubleshooting result

- [X] I have followed the troubleshooting section

**Comment by infokiller** [comment]
There is no keybinding to open the result in a new window, only in a new tab (`Ctrl`+`Space` by default). Does that work for you?

**Comment by thomasTAT** [comment]
![image](https://github.com/infokiller/web-search-navigator/assets/109513632/6178996f-0d24-43b5-b621-5386b99611e5)

**Comment by infokiller** [comment]
I'm not sure what this setting does, but it does not work for me, even when clicking a result with the mouse. Does it work for you?

**Comment by thomasTAT** [comment]
# result in news windows on
https://github.com/infokiller/web-search-navigator/assets/109513632/4d89948e-7cfb-4be9-a4f6-bfafc3350161

# result in news windows off

https://clipchamp.com/watch/zekjQIBVs3D

**Comment by thomasTAT** [comment]
Get what I want by using this plugin and control + enter but this make some side effect.
https://github.com/infokiller/web-search-navigator/assets/109513632/cf33f8fa-5734-4134-838e-047b55a4aa44

best regards developer.

**Comment by infokiller** [comment]
Thanks, glad you got it working!
