### ISSUE TITLE
Extension unavailable for Edge due to content infringement complaint

### ISSUE THREAD

**Issue by rik-smeets** [infokiller/web-search-navigator#59]
Yesterday, I received a content infringement complaint from Google regarding the extension for Microsoft Edge. It regards to the usage of the stylized Google 'G' which is used in the logo of the extension.

Because of this, I had to remove the extension from the Microsoft Store and it is therefore no longer discoverable / downloadable. 

I'm wondering: @infokiller, @mancze : did you receive similar complaints for for Chrome / Firefox? Maybe we should change the logo either way? After doing that, I can apply for re-submission of the extension in Edge.

**Comment by infokiller** [comment]
Nope, I didn't get such a complaint in the Chrome Web Store, but if we got a complaint I guess we should change the logo

**Comment by mancze** [comment]
Neither did I get a complaint. I agree with @infokiller - the logo should be changed.

**Comment by rik-smeets** [comment]
@infokiller Did you create the original logo? If so can you create a new one?

**Comment by infokiller** [comment]
Yes, I'll create a new one. In the meantime feel free to use anything else that is not problematic.

**Comment by rik-smeets** [comment]
Great! I'll just wait for the new logo, to prevent having to do multiple resubmissions.

**Comment by infokiller** [comment]
Damn, I uploaded non square icons... will fix it in 3-4 days (don't have the source file for the icon till then...)

**Comment by rik-smeets** [comment]
@infokiller I see the new logo still uses the 'G' from Google's logo, which uses a proprietary font (see https://en.wikipedia.org/wiki/Product_Sans). Do you think it's okay to use that font, or are you using a different font? I'm no expert in these matters and I think we can rather be safe than sorry to prevent other infringements.

**Comment by infokiller** [comment]
I'm not expert either, but the new 'G' is from shutterstock so I think it should be ok: https://www.shutterstock.com/image-vector/set-google-logo-circle-square-on-1050158639?src=library

Anyway, Google will now review the new logo, so let's see what they say.

**Comment by rik-smeets** [comment]
Thank you, I'll await their response before requesting resubmittal of the Edge extension.

**Comment by infokiller** [comment]
Nothing new yet, and yes the time this review is taking is really annoying.

**Comment by infokiller** [comment]
@rik-smeets did you try to resubmit the extension?

**Comment by rik-smeets** [comment]
@infokiller No, I did not. I was awaiting the resubmittal of the extension in the Chrome Web Store.

I do see that you changed the name of the repository/project. I would only further suggesting updating the assets and removing the stylized 'G' from Google from it as well, just be sure. After that, I would be happy to resubmit it.

**Comment by infokiller** [comment]
@rik-smeets I will work on a new icon without the G anyway (also the extension will become more general than just Google), but I think even the current one should be fine (it's from shutterstock). Why do you think the G is stylized in a way that may be problematic with Google?

**Comment by infokiller** [comment]
@rik-smeets I just updated the icon.

**Comment by rik-smeets** [comment]
@infokiller I didn't necessarily believe the 'G' would cause problems, but I'm rather safe than sorry when resubmitting the extension. Considering both the name and all assets are now changed, it should be good to go again!

I think I can get around to it this weekend. With a bit of luck, the extension should be up within a couple of weeks again for Edge. Yay!

**Comment by texastoland** [comment]
I love the extension! I really don't mean to be a troll but the new icon isn't distinguishable at toolbar size.

**Comment by infokiller** [comment]
@texastoland thanks for the feedback. I will soon commit a change that makes the icon colorful which should improve the situation.
Other than that, I'm not a designer by any mean, so contributions are welcome :)
