### ISSUE TITLE
Extension unavailable in the Chrome Web Store

### ISSUE THREAD

**Issue by williambarberjr** [infokiller/web-search-navigator#60]
Your link to the chrome extension page no longer works and I'm unable to find the extension in the chrome web store.

**Comment by infokiller** [comment]
Yes, I had to change the icon because of #59 
It should be up again within a week or so.

**Comment by anurbol** [comment]
Hi! I was "lucky" enough to reinstall my OS in these days, so now I am not able to use your great extension :) Is there a way to use it even it is not present in Google Play?

**Comment by infokiller** [comment]
Hi, you can clone this repo, build the chrome extension by running `yarn build --production`, and then loading the unpacked extension to Chrome- see also https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store

**Comment by anurbol** [comment]
Thanks! Good for me, I've just installed linux and removed windows.

**Comment by russelldavis** [comment]
This just bit me when I synced my extensions to a new profile and this one was mysteriously missing.

> It should be up again within a week or so.

Any update?

**Comment by infokiller** [comment]
No update yet, and I'm also negatively affected by this :(
Waiting for Google to do their review...

**Comment by louismartin** [comment]
Now even building the extension myself brings some errors:

```
Unrecognized manifest key '-ms-preload'.
Unrecognized manifest key 'applications'.
```
macOS 10.13.5
Google Chrome 67.0.3396.99 (Official Build) (64-bit)

**Comment by infokiller** [comment]
There errors are more like warnings, the extension should still work (at least it does for me even with those errors shown by Chrome)

**Comment by rik-smeets** [comment]
Yes, those errors occur because Chrome does not recognize those keys, but they are necessary for other browsers. Probably the same occurs in other browsers for Chrome specific manifest keys. You can safely ignore the warnings.

**Comment by beardedlinuxgeek** [comment]
Could you just build the extension and do a release on github? That way users don't need to install yarn and gulp and build it themselves.

**Comment by infokiller** [comment]
@beardedlinuxgeek I did a release for Chrome: https://github.com/infokiller/google-search-navigator/releases/tag/0.2.10

**Comment by denolfe** [comment]
Unfortunately, loading an unpacked extension on Windows causes a nagging pop-up every time Chrome is launched. I would love to see this put back into the store.

**Comment by tedzhu** [comment]
Anything we can do to accelerate this process?

**Comment by infokiller** [comment]
Not that I know of :(

**Comment by jpotocki** [comment]
@infokiller Can you anything to make this extension back to the Chrome Web Store?

I found your extension best out of any similar solutions but without the Store presence it does not update automatically nor syncs with other Chrome installations, where I am using my Chrome loginb :-(

**Comment by infokiller** [comment]
I know this issue is causing a big annoyance and I'd really like it to be resolved quickly as well, but I'm not sure what to do at this point. Emailed the Chrome Webstore multiple times about this and they seem to ignore me :(

**Comment by afilp** [comment]
Could a submission under a totally different name/icons/etc. help?

**Comment by infokiller** [comment]
I'd like to avoid a new submission, mainly because all the existing users of the extension (the ones that installed it before it was removed) will no longer get any updates, which means it will be broken.
If they keep being unresponsive I will break eventually and do it, but I'll probably wait 1-2 months before doing so in hopes that this will be settled...

**Comment by rik-smeets** [comment]
I was also thinking of that @afilp, but I understand that @infokiller would like to wait a bit longer.

If rebranding is necessary, I would propose to make it more generic, which would have the advantage that the extension could expand itself to other search providers. I use Bing sometimes too for example, which does have some basic keyboard navigation in itself, but not a great as this extension in my opinion.

So I would call it something like: `Keyboard navigation for search engines` or something. Yeah, quite bland, but should be safe and is very descriptive at the very least.

**Comment by rik-smeets** [comment]
@infokiller Since you've renamed the extension and updated the assets (like the logo), are you resubmitting the extension again too?

**Comment by infokiller** [comment]
No, I'm trying to use the existing submitted extension- it's possible to do all the updates I've made including the rename.

**Comment by rik-smeets** [comment]
@infokiller Good one, I'll check if that's possible for Edge too.

**Comment by infokiller** [comment]
And finally, the extension is back in the store! Closing.

**Comment by jpotocki** [comment]
> And finally, the extension is back in the store! Closing.

I am very happy about it!!!
