### ISSUE TITLE
Picking up search results embedded in "People also ask"

### ISSUE THREAD

**Issue by alexbarrett** [infokiller/web-search-navigator#79]
![image](https://user-images.githubusercontent.com/114549/45883192-4683d380-bda8-11e8-8a41-e2f56f0fd73f.png)

The results are included in the navigation even when the questions are collapsed, so you have to press down several times to get to the first real result. The HTML structure of these embedded results on this particular page is similar to the main search results. I have come across other "People also ask" boxes that were not included in the navigable result set.

**Comment by alexbarrett** [comment]
I've been unable to replicate this. It only seems to happen when the extension is reloaded with the search results already open. I assume this means that the "People also ask" box is added dynamically after the extension runs under normal circumstances.

**Comment by infokiller** [comment]
Thanks! I also ran into this a few times and I definitely want to fix it.
Let's keep it open for now and I'll try to make progress when I have more time.
