### ISSUE TITLE
Proposal: Add option for Image Size

### ISSUE THREAD

**Issue by mniborsk** [infokiller/web-search-navigator#91]
Maybe it's just me, but I'm often looking for high resolution images and find myself going to Tools - Size - Larger than - 2MP / 4MP etc. A keyboard shortcut would be very helpful (as is this extension in general, thank you!).

![image](https://user-images.githubusercontent.com/3584003/48435145-80df7080-e75a-11e8-8772-77c5ab2d7834.png)

**Comment by infokiller** [comment]
Sounds good to me. I doubt I'll have time to work on this soon, but I welcome PRs, though it should probably wait till the typescript migration is done (#75), which I expect to happen in the next 1-2 weeks.

**Comment by yuanLeeMidori** [comment]
Hi! I'm interested in working on this feature. Please let me know if you still need help. Thank you.

**Comment by infokiller** [comment]
Thanks @yuanLeeMidori that would be great, feel free to work on this, and see the [dev notes](https://github.com/infokiller/web-search-navigator#development).

**Comment by yuanLeeMidori** [comment]
Hi, @infokiller,
I believe the options for **Larger than** and **Exact size** have been removed from Google Chrome last year. In that case, I would only be working on the keyboard shortcuts of **Large**, **Medium**, and **Icon**. 

If this is okay for you, I will send the PR after I run the modified files with ESLint. Thank you.

**Comment by infokiller** [comment]
Sure, no pressure, and I welcome any contributions so thank!

**Comment by mniborsk** [comment]
Hi @yuanLeeMidori, thank you so much for working on this!

In case it helps, it is still possible to filter by precise resolution via the url. For example, adding `&tbs=isz:lt,islt:4mp` at the end of the url in an image search page looks for images that are at least 4 megapixels in size. That string can be modified for any positive integer. I only mention this because the default "Large" option in Google's image search returns images as small as 900x900 pixels. 

Thanks again and have a great day!

![image](https://user-images.githubusercontent.com/3584003/96447381-338e9800-11e8-11eb-9076-48e862d1eb32.png)
