### ISSUE TITLE
No option to navigate special results (Twitter, images, etc)

### ISSUE THREAD

**Issue by VarunAgw** [infokiller/web-search-navigator#92]
So far I have noticed it to skip

- Twitter result entry
- Images for %keyword%
- Search pages number (except next)

They should be included in arrow navigation too.

**Comment by infokiller** [comment]
Can you please elaborate?
You want it to skip more things? which ones?

**Comment by VarunAgw** [comment]
No! I want it to include these too.

**Comment by infokiller** [comment]
Got it now. I plan to add options for specifying whether to include some of these things.

**Comment by infokiller** [comment]
I just added support in the master branch for cards in the regular search results, including Twitter, Top Stories, and Videos.
I won't add search pages for now as I'm not sure if there's real interest in this feature, but note that you can navigate the pages with keybindings.
Note sure what you meant earlier by "Images for %keyword%", can you please clarify?
